# Generated by Django 5.0.1 on 2024-02-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='assignment',
        ),
        migrations.AddField(
            model_name='correction',
            name='assignment_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluator.assignmentinstance'),
        ),
    ]
