# Generated by Django 5.0.1 on 2024-02-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_remove_correction_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='assignment_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_assignment_instance', to='evaluator.assignmentinstance'),
        ),
    ]
