# Generated by Django 5.0.1 on 2024-01-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_tutor_groups_tutor_is_active_tutor_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexercise',
            name='dueFrom',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='dueTo',
            field=models.DateField(null=True),
        ),
    ]
