# Generated by Django 5.0.1 on 2024-02-15 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_alter_correction_assignment_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinstance',
            old_name='directly_assigned_students',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='class_group',
        ),
        migrations.AlterField(
            model_name='assignmentinstance',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_instances', to='evaluator.courseinstance'),
        ),
    ]
