# Generated by Django 5.0.1 on 2024-02-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_rename_directly_assigned_students_courseinstance_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='students',
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default=0)),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.courseinstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.student')),
            ],
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='xstudents',
            field=models.ManyToManyField(through='evaluator.CourseEnrollment', to='evaluator.student'),
        ),
    ]
