# Generated by Django 5.0.1 on 2024-01-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_courseexercise_duefrom_courseexercise_dueto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexercise',
            name='dueFrom',
        ),
    ]
