# Generated by Django 5.0.1 on 2024-02-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_remove_courseinstance_students_courseenrollment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinstance',
            old_name='xstudents',
            new_name='students',
        ),
    ]
