# Generated by Django 5.0.1 on 2024-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_user_degree_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='draft',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
