# Generated by Django 5.0.1 on 2024-01-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0005_remove_courseexercise_duefrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseexercise',
            old_name='dueTo',
            new_name='due_to',
        ),
    ]
