# Generated by Django 5.0.1 on 2024-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0006_assignment_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentinstance',
            options={'ordering': ['assignment__nr']},
        ),
        migrations.RemoveField(
            model_name='previousdeduction',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='previousdeduction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='previousdeduction',
            name='points',
        ),
        migrations.AddField(
            model_name='previousdeduction',
            name='draft',
            field=models.JSONField(null=True),
        ),
    ]
