# Generated by Django 5.0.1 on 2024-01-14 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0006_rename_dueto_courseexercise_due_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.JSONField()),
                ('state', models.CharField(choices=[('o', 'other'), ('ip', 'in progress'), ('ns', 'not submitted'), ('c', 'completed')], default='o', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.course')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluator.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
