# Generated by Django 5.0.1 on 2024-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0006_rename_xstudents_courseinstance_students'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course_instance'), name='course_enrollment_pk'),
        ),
    ]
