# Generated by Django 5.0.1 on 2024-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_previous_deductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='points',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
