# Generated by Django 5.0.1 on 2024-02-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0007_courseenrollment_course_enrollment_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_tutor', to='evaluator.tutor'),
        ),
    ]
