# Generated by Django 5.0.1 on 2024-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_alter_correction_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='assignments',
            field=models.ManyToManyField(through='evaluator.AssignmentInstance', to='evaluator.assignment'),
        ),
    ]
