# Generated by Django 5.1.1 on 2024-09-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0008_correction_points_adjustment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('start_year', 'degree_program')},
        ),
    ]
