# Generated by Django 5.0.1 on 2024-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0009_courseinstance_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
