# Generated by Django 5.1.1 on 2024-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0009_feature_39'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gitlab_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('FEATURE', 'Feature'), ('BUG', 'Bug')]),
        ),
    ]
