# Generated by Django 5.1.1 on 2024-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0010_feature_44'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='group',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
