# Generated by Django 5.1.1 on 2024-09-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0011_feature_40'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='group',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='previousdeduction',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluator.assignment'),
        ),
    ]
