# Generated by Django 5.0.1 on 2024-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0011_alter_correction_points_tutorassignment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tutorassignment',
            name='valid_group_number',
        ),
        migrations.AlterUniqueTogether(
            name='tutorassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tutorassignment',
            name='_groups',
            field=models.TextField(default='[]'),
        ),
        migrations.RemoveField(
            model_name='tutorassignment',
            name='group',
        ),
    ]
