# Generated by Django 5.0.1 on 2024-02-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0012_remove_tutorassignment_valid_group_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorassignment',
            unique_together={('tutor', 'assignment_instance')},
        ),
    ]
