# Generated by Django 5.1.1 on 2024-10-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0012_feature_62'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['nr']},
        ),
    ]
