# Generated by Django 5.1.1 on 2024-10-07 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0013_feature_65'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseenrollment',
            options={'ordering': ['student__last_name', 'student__first_name']},
        ),
    ]
