# Generated by Django 5.1.1 on 2024-10-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0014_bug_70'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='points',
        ),
    ]
