# Generated by Django 5.1.1 on 2024-11-08 17:59

from django.db import migrations, models

def populate_file_name(apps, schema_editor):
    CourseInstance = apps.get_model('evaluator', 'CourseInstance')
    for instance in CourseInstance.objects.all():
        if not instance.file_name:  # Only update if it's empty
            instance.file_name = instance.course.file_name
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0015_bug_73'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(populate_file_name)
    ]
