# Generated by Django 5.1.1 on 2024-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0016_feature_82'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
