# Generated by Django 6.0 on 2025-12-19 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0017_feature_82'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='late_submission_penalty',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='correction',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
