from .assignment_model import Assignment
from .assignment_instance_model import AssignmentInstance
from .class_group_model import ClassGroup
from .correction_model import Correction
from .course_enrollment_model import CourseEnrollment
from .course_instance_model import CourseInstance
from .course_model import Course
from .degree_program_model import DegreeProgram
from .previous_deduction_model import PreviousDeduction
from .report_model import Report
from .student_model import Student
from .tutor_assignment_model import TutorAssignment
from .user_degree_program_model import UserDegreeProgram